config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'
  resources :teams
  resources :members

  get 'meeting_mornings/:id' => "meeting_mornings#index", as: "meeting_mornings"
  get 'meeting_mornings/:id/new' => "meeting_mornings#new", as: "new_meeting_mornings"
  post 'meeting_mornings/:id' => "meeting_mornings#create"

  get 'meeting_afternoons/:id' => "meeting_afternoons#index", as: "meeting_afternoons"
  get 'meeting_afternoons/:id/new' => "meeting_afternoons#new", as: "new_meeting_afternoons"
  post 'meeting_afternoons/:id' => "meeting_afternoons#create"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gestao de Serviços 
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->

app/views/shared/_page_title.html.erb
            <div class="page-title">
              <div class="title_left">
                <h3><%=t controller_name %></h3>
              </div>
              <!--
              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
              -->
            </div>

app/views/shared/_sidebar.html.erb
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
            <%= link_to root_path, class: "site_title" do %>
              <i class="fas fa-chart-line"></i> <span>Ger. de Daily</span>
            <% end %>
             
            </div>

            <div class="clearfix"></div>

            <% if current_user %>
              
         

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <%= image_tag  "img.jpg", alt: "...", class: "img-circle profile_img" %>
              </div>
              <div class="profile_info">
                <span>Bem Vindo,</span>
                <h2><%= current_user.email %></h2>
              </div>
              <div class="clearfix"></div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>Opções</h3>
                <ul class="nav side-menu">
                  <li>
                    <%= link_to teams_path do %>
                      <i class="fas fa-lg fa-clipboard-list"></i> Equipes
                    <% end %>
                  </li>                 
                  <li>
                    <%= link_to members_path do %>
                      <i class="fas fa-lg fa-users"></i> Membros
                    <% end %>
                  </li>                 
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->
               <% end %>
          </div>
        </div>

app/views/shared/_top_navigation.html.erb
        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>
              <% if current_user %>
                <ul class="nav navbar-nav navbar-right">
                  <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                      <%= image_tag  "img.jpg", alt: "..." %><%= current_user.email %>
                      <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                      <li>
                          <%= link_to   destroy_user_session_path, method: :delete do %>
                              <i class="fas fa-sign-out-alt pull-right"></i> Sair
                          <% end %>
                      </li>
                    </ul>
                  </li>

                </ul>
              <% end %>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->