config/routes.rb
Rails.application.routes.draw do
  root 'teams#index'
  resources :teams
  resources :members

  get 'meeting_mornings/:id' => "meeting_mornings#index", as: "meeting_mornings"
  get 'meeting_mornings/:id/new' => "meeting_mornings#new", as: "new_meeting_mornings"
  post 'meeting_mornings/:id' => "meeting_mornings#create"

  get 'meeting_afternoons/:id' => "meeting_afternoons#index", as: "meeting_afternoons"
  get 'meeting_afternoons/:id/new' => "meeting_afternoons#new", as: "new_meeting_afternoons"
  post 'meeting_afternoons/:id' => "meeting_afternoons#create"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord

    belongs_to :user
    belongs_to :team
    has_many :meeting_mornings, dependent: :delete_all
    has_many :meeting_afternoons, dependent: :delete_all
    
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    before_action :authenticate_user!

  def index
    @members = Member.where(user_id: current_user.id)
    respond_to do |format|
      format.html
      format.json { render json: MemberDatatable.new(view_context, user: current_user) }
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    @member.user_id = current_user.id
    begin
      if @member.save
        flash[:success] = 'Membro cadastrada com sucesso!'
      end
    rescue => exception
      flash[:error] = 'Erro ao cadastrada membro!'
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
     @member = Member.find(params[:id])
    begin
      if @member.update_attributes(member_params)
        flash[:success] = 'Membro atualizada com sucesso!'
      end
    rescue => exception
      flash[:error] = 'Erro ao atualizar membro!'
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.meeting_mornings.delete_all
    @member.meeting_afternoons.delete_all
    begin
      if @member.delete
        flash[:success] = 'Membro deletada com sucesso!'
      end
    rescue => exception
      flash[:error] = 'Erro ao deletar membro!'
    end
  end

  private

  def member_params
    params.require(:member).permit(:email, :team_id)
  end
end

app/views/members/_form.html.erb
<div id="add-member" class="modal fade in" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel2">Funcionário</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <%= simple_form_for @member, remote: true, html: { class: "form-horizontal form-label-left" }, wrapper: false do |f| %>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="member[email]">Email<span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.input :email , placeholder:"Email", label: false, wrapper: false,input_html: { :class => "form-control col-md-7 col-xs-12" },required: true %>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="member[team]">Equipe <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.association :team, collection: Team.all.order(:name), prompt: "Escolha uma Equipe", label: false, wrapper: false,input_html: { :class => "form-control col-md-7 col-xs-12" },required: true %>
                        </div>
                    </div>											  
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default float-right" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">Salvar</button>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/members/create.js.erb
<% flash.each do |type, message| %>
  new PNotify({
              title: '<%= notification_color(type) %>',
              text: '<%= message %>',
              type: '<%= notification_color(type) %>',
              styling: 'bootstrap3'
          });
    
  $('#add-member').modal('hide');
  $('.dataTable').each(function() {
    dt = $(this).dataTable();
    dt.fnDraw();
  });
<% end %>

<% flash.discard  %>

app/views/members/destroy.js.erb
<% flash.each do |type, message| %>
  new PNotify({
              title: '<%= notification_color(type) %>',
              text: '<%= message %>',
              type: '<%= notification_color(type) %>',
              styling: 'bootstrap3'
          });
    
    table_member.fnDraw();
<% end %>

<% flash.discard  %>

app/views/members/edit.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/members/index.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>Membros</h2>
                <div class="box-tools pull-right">
                    <%= link_to  new_member_path, class:"btn btn-success pull-right", remote: true do %>
                        Adicionar
                    <% end %>
                </div>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <p class="text-muted font-13 m-b-30">
                Lista de membros cadastradas no sistema
            </p>
            <table id="member-datatable" class="table table-striped table-bordered "  data-source="<%= members_path(format: :json) %>">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Email</th>
                        <th>Equipe</th>
                        <th colspan="4" class="text-center">Ações</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>


<%= content_for :javascripts do %>
  jQuery(document).ready(function() {
    table_member = $('#member-datatable').dataTable({
      "language": {
        "url": "https://cdn.datatables.net/plug-ins/1.10.16/i18n/Portuguese-Brasil.json"
      },
      "processing": true,
      "serverSide": true,
      "ajax": $('#member-datatable').data('source'),
      'paging': true,
      'lengthChange': true,
      'searching': true,
      'ordering': true,
      'info': true,
      'autoWidth': false,
      "columns": [
        {"data": "id"},
        {"data": "email"},
        {"data": "name"},
        { "data": "morning", "sClass": "action_table text-center"},
        { "data": "afternoon", "sClass": "action_table text-center"},
        { "data": "edit", "sClass": "action_table text-center"},
        { "data": "delete", "sClass": "action_table text-center"}
      ]
    });
  });
<% end %>

app/views/members/new.js.erb
$('<%= j render "form" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/members/update.js.erb
<% flash.each do |type, message| %>
  new PNotify({
              title: '<%= notification_color(type) %>',
              text: '<%= message %>',
              type: '<%= notification_color(type) %>',
              styling: 'bootstrap3'
          });

  $('#add-member').modal('hide');
  $('.dataTable').each(function() {
    dt = $(this).dataTable();
    dt.fnDraw();
  });
<% end %>

<% flash.discard  %>